### ISSUE TITLE
Why 'X-Raw-Filesystem-API' is Undocumented?

### ISSUE THREAD

**Issue by pamubay** [thecoshman/http#104]
This is really nice tool. 

- small single binary without dependencies
- Serve a directory over HTTP server (and light on memory :+1: )
- Able to do PUT, DELETE Operations on file/directory. (even better we also have `MKCOL`) :+1: :
- Able to use your own frontend (`index.html`,`js`,`css`)

But i'm almost left this tool because i didnt find any documentation about getting directory list via json. because it's really important in building my single page application

If it's not because i'm bored, i browsing the source files until i found this function named [`handle_get_raw_fs_dir()`](https://github.com/thecoshman/http/blob/fa9d6674f9e210b622ede743fe0b3a1c65e2f92f/src/ops/mod.rs#L627-L628). Although I have zero knowledge of rust, i follow all the import path until i found this [`X-Raw-Filesystem-API`](https://github.com/nabijaczleweli/rfsapi-rs/blob/1bdb5f8dbca0f49510e74859acea9e44a19be3ee/src/lib.rs). :cry: 

I hope the maintainer could put the documentation of this feature.

For the maintainers, Thanks for your hard work. :+1: 
Have a Nice Day! :sun_with_face:

**Comment by nabijaczleweli** [comment]
Thank you for your interest!

I haven't documented the JSON format, since, well, I didn't expect anyone except [D'Oh](https://github.com/thecoshman/doh) to use this, back in 2017 (three years ago, dang!) – I'll write some documentation now.

**Comment by nabijaczleweli** [comment]
Take a look at https://rawcdn.githack.com/nabijaczleweli/rfsapi-rs/doc/rfsapi/index.html – I tried my best, but if something's unclear or not obvious I'd really appreciate the feedback!

**Comment by pamubay** [comment]
I'm actually prefer simple documentation for the end-user like me (not developer). Just a simple explanation in README.md is more than enough.

Thank You. :handshake:

**Comment by nabijaczleweli** [comment]
Alright, I also added a short description here: https://github.com/nabijaczleweli/rfsapi-rs#format-brief – tried to keep it short and sweet; is that more like you envisioned?

**Comment by pamubay** [comment]
looks great!:100: 

Thank You, :smiley:

**Comment by nabijaczleweli** [comment]
Released in [`v1.9.2`](https://github.com/thecoshman/http/releases/tag/v1.9.2)!
