### ISSUE TITLE
Segfaults when encoding files (sometimes? always?) on musl

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#109]
Following these two comments from @adrianisuru:
https://github.com/thecoshman/http/pull/108#issuecomment-630406049
https://github.com/thecoshman/http/issues/107#issuecomment-629983914

**Comment by nabijaczleweli** [comment]
This looks like it was a fuckup in the way I allocate in `md6` (see last screenshot in particular, where I represented the struct as-was instead of just adding the member sizes; genuinely surprised this hadn't happened earlier).

![image](https://user-images.githubusercontent.com/6709544/83944073-1d67d880-a801-11ea-90f1-bcabfd76d61b.png)
![image](https://user-images.githubusercontent.com/6709544/83944097-35d7f300-a801-11ea-989a-52628c6cfacd.png)
![image](https://user-images.githubusercontent.com/6709544/83944166-b991df80-a801-11ea-8e9e-119a6ccd4520.png)
![image](https://user-images.githubusercontent.com/6709544/83944208-f6f66d00-a801-11ea-93ad-a416e2ed1cc0.png)
![image](https://user-images.githubusercontent.com/6709544/83944255-4b99e800-a802-11ea-9a04-e7b86817c492.png)
![image](https://user-images.githubusercontent.com/6709544/83944281-9b78af00-a802-11ea-8846-3918354db271.png)
![image](https://user-images.githubusercontent.com/6709544/83944283-9e739f80-a802-11ea-8f58-fd2a0365ff7f.png)
![image](https://user-images.githubusercontent.com/6709544/83944309-d549b580-a802-11ea-9af6-90fdcc210ac6.png)
![image](https://user-images.githubusercontent.com/6709544/83944317-f6120b00-a802-11ea-9a53-51df3ee059a7.png)
![image](https://user-images.githubusercontent.com/6709544/83944327-0fb35280-a803-11ea-9be3-3c80e91ba9fb.png)
![image](https://user-images.githubusercontent.com/6709544/83944520-4b9ae780-a804-11ea-9b64-b93716ae8fb4.png)
![image](https://user-images.githubusercontent.com/6709544/83944608-0aef9e00-a805-11ea-93eb-ff5da48b9e48.png)
![image](https://user-images.githubusercontent.com/6709544/83944636-4b4f1c00-a805-11ea-8aa3-266318323077.png)
![image](https://user-images.githubusercontent.com/6709544/83944637-4e4a0c80-a805-11ea-8127-bc4e4a3b97de.png)
![image](https://user-images.githubusercontent.com/6709544/83944645-69b51780-a805-11ea-97b6-9f7e99e9a870.png)
![image](https://user-images.githubusercontent.com/6709544/83945084-71c28680-a808-11ea-8079-8c1ef3517ca3.png)

**Comment by adrianisuru** [comment]
It works!

**Comment by nabijaczleweli** [comment]
Delightful! Thanks for testing!

**Comment by nabijaczleweli** [comment]
Released in [`v1.9.3`](https://github.com/thecoshman/http/releases/tag/v1.9.3).
