### ISSUE TITLE
Hot-reload html pages

### ISSUE THREAD

**Issue by pickfire** [thecoshman/http#112]
https://github.com/kettle11/devserver is another simple http serving similar to this project, it features something not available in http which is hot-reloading, when some files are changed, it signals the html to reload through javascript injected into the html. Currently http crate have more features that is not available in devserver but however this features seems useful.

CC @kettle11

**Comment by nabijaczleweli** [comment]
The indices have too much JS already.

If you mean you want to mangle the served files then I don't know what to tell you except to laugh.

**Comment by thecoshman** [comment]
Yeah, agreed. This isn't a feature I would want to see in this project.

You can however simulate this sort of thing simply by writing the content yourself and then use any server. You just need a background JS script (that is served as part of the page) that can keep polling the server for fresh content and when it detects that content has been changed, update the DOM

**Comment by pickfire** [comment]
Is it possible to allow having an argument to provide this, at least users does not need to do scripting and have the power of `devserver`.

**Comment by nabijaczleweli** [comment]
There is not. `http` will *never* alter responses in relation to the on-disk files they correspond to.

**Comment by kettle11** [comment]
To provide some more context: This is the snippet `devserver` inserts into outgoing `.html` (unless the feature is turned off): 

```html
<script>
    // This code is inserted by devserver to enable reloading.
    const socket = new WebSocket("ws://" + window.location.hostname + ":8129");
    socket.addEventListener('open', function (event) { console.log("Reloading enabled!"); });
    socket.addEventListener('message', function (event) { location.reload(); });
</script>
```
It is appended to the end of `.html` which seems to work without any negative repercussions.

**Comment by nabijaczleweli** [comment]
It also hard-codes `hostname:port` and requires the process to (a) handle WebSuckets and (b) watch arbitrary files. As I said: this will not happen. Here's a snippet to get you started off that does the same thing using RFSAPI, feel free to add it to your HTML files and they'll auto-reload, so long as the backing server is `http`:
```javascript
const reload_req = new XMLHttpRequest();
let latest = null;
reload_req.onload = () => {
	if(reload_req.responseText) {
		let resp =  JSON.parse(reload_req.responseText);
		let mtime = resp.files[0].last_modified;
		if(!latest)
			latest = mtime;
		else if(latest != mtime)
			window.location.reload();
	}

	setTimeout(() => {
		reload_req.open("GET", window.location.toString());
		reload_req.setRequestHeader("X-Raw-Filesystem-API", 1);
		reload_req.setRequestHeader("Cache-Control", "no-cache");
		reload_req.send();
	}, reload_req.responseText ? 500 : 0);
};
reload_req.onload();
```

**Comment by erooke** [comment]
For future travelers the above script needed a minor tweak to work for me. The page constantly reloaded due to minor inconsistencies with the `mtime`. Parsing the `last_modified` field to a datetime fixed the problem:

```js
const reload_req = new XMLHttpRequest();
let latest = null;
reload_req.onload = () => {
    if(reload_req.responseText) {
        let resp =  JSON.parse(reload_req.responseText);
        let mtime = Date.parse(resp.files[0].last_modified);
        if(!latest)
            latest = mtime;
        else if(latest != mtime)
            window.location.reload();
    }

    setTimeout(() => {
        reload_req.open("GET", window.location.toString());
        reload_req.setRequestHeader("X-Raw-Filesystem-API", 1);
        reload_req.setRequestHeader("Cache-Control", "no-cache");
        reload_req.send();
    }, reload_req.responseText ? 500 : 0);
};
reload_req.onload();
```

Apologies for the necro-bump...
