### ISSUE TITLE
serve .html on extensionless paths?

### ISSUE THREAD

**Issue by phi-fell** [thecoshman/http#113]
I'm using this to test a site locally, and (as many webservers do) going to e.g. `/some-file` serves `/some-file.html` whereas this crate serves a 404

Is there an option for this that I missed? and if not, could one be added?

**Comment by nabijaczleweli** [comment]
Apologies for the delay; can you try current `develop` (at least 4b6f57d23b762eb093ef9ef2018bf331472776d0) with the `-x`/`--strip-extensions`?

**Comment by phi-fell** [comment]
No worries! That works perfectly! Thank you!

**Comment by nabijaczleweli** [comment]
Cool. Released in [`v1.10.0`](https://github.com/thecoshman/http/releases/tag/v1.10.0)!
