### ISSUE TITLE
Escape square brackets in index URLs

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#119]
> [14:19] Danny: @((наб *)(войд)())() you think httplz tool could escape brackets in filenames like [ and ] in the generated index page. Kind of a weird request lol since it's a combination of weird specs, browsers, and other apps having stricter URL parsing
> [14:20] Danny: apparently on firefox if you long tap something to send a URL to another app it doesn't escape the brackets
> [14:20] Danny: and VLC chokes on brackets cause they're invalid in URLs

**Comment by thecoshman** [comment]
Does this need to be extended to make sure that all invalid/unsafe characters are escaped form the URL?

**Comment by nabijaczleweli** [comment]
No, we already do that.

**Comment by nabijaczleweli** [comment]
Fix ACKed by reporter

**Comment by nabijaczleweli** [comment]
Released in [v1.10.1](https://github.com/thecoshman/http/releases/tag/v1.10.1).
