### ISSUE TITLE
Name of the binary clashes with httpie

### ISSUE THREAD

**Issue by 5c0tt-b0t** [thecoshman/http#128]
Hi! thank you for this great little server!!! its really appreciated!
I had to clone the repo, build it and rename the `http` binary to something else as its the same name as httpie's `http` binary, not sure if this will now affect updating it now as its a different name?!?
Perhaps, as `httpie` is so popular (50,000 stars & 3,500 forks) it would be wise to re-consider the binary's name to stop the conflict, the repo can still be named http if you wish, but the binary atleast should be changed to something else, httpie provides two binaries: `http` & `https`.
Thank you!

**Comment by nabijaczleweli** [comment]
Install just the `httplz` binary, then. This isn't your (indeed, it's nobody's) namespace to enforce.

**Comment by griwes** [comment]
Uhhhh, so a project that's not named http should own the name? What a curious take on the issue. (And by "curious" I mean all but that.)

**Comment by 5c0tt-b0t** [comment]
Strange, not sure why this was taken so wrong, does it sound like a complaint?!? just giving some kind advice!
> This isn't your (indeed, anyone's) namespace to enforce.
Im not trying to enforce anything, nor did I.
> Uhhhh, so a project that's not named http should own the name? What a curious take on the issue. (And by "curious" I mean all but that.)
What a *curious* response. Did I emply that they do own or should own the name?? no.
Just some advice before this repo gets the popularity it deserves and you end up with more people running into this problem. Shame it wasnt recieved well, for some unknown reason?
Good luck guys, with attitudes like that, you may need it.

**Comment by thecoshman** [comment]
Please note we have previously resolved this issue in #35

**Comment by 5c0tt-b0t** [comment]
@thecoshman thank you for a normal response, I am sorry for not seeing that issue in closed, I apologise, again just advice, perhaps adding this info to the ReadMe would be helpful to those installing, many of them may have httpie also.
