### ISSUE TITLE
Handle PATCH

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#13]
HTTP defines PATCH in [RFC5789](https://tools.ietf.org/html/rfc5789). Support therefor would go a long way towards full write support.

**Comment by nabijaczleweli** [comment]
This seems to be pretty content-specific, too. We could support basic GNU/Git-style patches for text files and that's about as far as would be in scope. Or we could not support it at all.

**Comment by thecoshman** [comment]
This should be closed for now, it's too open ended as to how to apply the data provided. POST however is simpler, they upload a file and it is persisted, the only difficult part is determining the "where", but I think that can be defined well enough that we can implement POST
