### ISSUE TITLE
Feature request: Specify headers

### ISSUE THREAD

**Issue by blakehawkins** [thecoshman/http#130]
I'd like to be able to do `httplz . --header "Access-Control-Allow-Origin: *"` for example

**Comment by nabijaczleweli** [comment]
Can you try current `develop` branch (at least 820570db0a046835d7d28bb94655551db1b66026)? Should work exactly like you wrote it.

**Comment by blakehawkins** [comment]
Works great, thanks!

**Comment by nabijaczleweli** [comment]
Hog. Released in [`v1.12.0`](https://github.com/thecoshman/http/releases/tag/v1.12.0)
