### ISSUE TITLE
🚨 Potential Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')

### ISSUE THREAD

**Issue by huntr-helper** [thecoshman/http#133]
👋 Hello, @thecoshman - a potential medium severity Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting') vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-thecoshman/http** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by nabijaczleweli** [comment]
an attacker that.... has write access to the server? i mean, sure, it looks bad, but that's a tad inflated

**Comment by thecoshman** [comment]
I agree this is not a serious concern. The user who is creating this file and running `http` has access to the server and is running for their own purposes. This is a minor annoyance at most.

**Comment by nabijaczleweli** [comment]
Released in [`v1.12.1`](https://github.com/thecoshman/http/releases/tag/v1.12.1). Thanks for the report!
