### ISSUE TITLE
Cors method configuration

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [thecoshman/http#136]
Hello,

I cannot pass the parameter:
```
-H "Access-Control-Allow-Method: GET,POST"
```

due to the comma, the VALUE is detected as not correct.

Best regards,
Marc-Antoine

**Comment by nabijaczleweli** [comment]
uhoh, clap documentation fucky wucky moment!

**Comment by nabijaczleweli** [comment]
Released in [`v1.12.2`](https://github.com/thecoshman/http/releases/tag/v1.12.2)!
