### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by cyqsimon** [thecoshman/http#142]
I made an AUR package, for people who want to do it this way.

https://aur.archlinux.org/packages/httplz

**Comment by cyqsimon** [comment]
Also, are you interested in being added as a maintainer so you'll have write access? Of course please feel free to decline.

**Comment by nabijaczleweli** [comment]
No thanks, I have no relation to Arch and would rather it stay this way.

**Comment by nabijaczleweli** [comment]
Noted in [`v1.12.3`](https://github.com/thecoshman/http/releases/tag/v1.12.3).
