### ISSUE TITLE
MD6?

### ISSUE THREAD

**Issue by Kijewski** [thecoshman/http#144]
Hi, I wonder why you chose MD6 instead of a better researched, and much more widely used cryptographic hash function like BLAKE2b?

**Comment by nabijaczleweli** [comment]
It was on my mind because I'd just written md6-rs, I guess. Making it BLAKE3 or whatever is like a six-line change. Why?

**Comment by Kijewski** [comment]
> It was on my mind because I'd just written md6-rs

Ah, I didn't notice that both projects are written by you. Yes, that's as good a reason as as any, I guess. :)

I was just interested, because it's probably the first time I saw MD6 mentioned in the wild since it was withdrawn from the SHA-3 competition.

**Comment by nabijaczleweli** [comment]
Replaced with BLAKE3 in [`v1.12.3`](https://github.com/thecoshman/http/releases/tag/v1.12.3).
