### ISSUE TITLE
Spawning TLS key generation

### ISSUE THREAD

**Issue by MartMet** [thecoshman/http#146]
Hey,

great work, i really appreciate this tool. 

Just a question to the option  `http --gen-ssl`

Iam on windows 10 and receive this error:
`Spawning TLS key generation process failed: program not found.` 

I looked into the codebase but could not find any reference to which subprocess needs to be spawned. 

Which tool is used for this option?

**Comment by nabijaczleweli** [comment]
https://github.com/thecoshman/http/blob/v1.12.4/src/ops/mod.rs#L1500
