### ISSUE TITLE
Define index handling

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#16]
We should try to find an RFC that actually defines how servers are meant to handle this and consider how modern browsers handle it as well. I think that strictly speaking, browsers do not ask for 'folders', they automatically append `index.html`... that might also just be a convention, I don't see any reason why it should have that name. 

Asking for a folder might technically warrant some sort of 4XX response, as the client shouldn't have asked for a folder. 

Also need to consider how to handle extensions, if the client asks for `index.html` but there is only an `index.htm`, do we return that instead?

**Comment by nabijaczleweli** [comment]
I didn't find anything in the [RFC Index](https://tools.ietf.org/rfc), but:
  * [Here](http://httpd.apache.org/docs/trunk/mod/mod_dir.html#directoryindex)'s how Apache handles this -- default `index.html`, but extensible, so not really something for us.
  * nginx does [similarly](https://www.nginx.com/resources/admin-guide/serving-static-content).
  * Something called `hapijs` does [exactly the same](https://github.com/hapijs/inert#the-directory-handler)
