### ISSUE TITLE
Create directory button for non-WebDAV

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [thecoshman/http#163]
Currently the only way (at least that I found) to create directories without WebDAV enabled (i.e. without -d) is to drag&drop a folder with some file in it, which is quite annoying, especially when you don't have any graphical file manager.

**Comment by nabijaczleweli** [comment]
I've also wanted advanced management before. Can you try the current `develop` branch (at least 987cd1a2b7bd49d37f8f35eabf21c5cb1d040340) and -D/--convenient-webdav?

**Comment by rozbrajaczpoziomow** [comment]
Seems like `RENAME` should be implemented with -D instead of `PROPPATCH`.

**Comment by rozbrajaczpoziomow** [comment]
Seems to work after https://github.com/thecoshman/http/commit/f5faae4710f99fa42b23992e773ab172a74e17d5.

**Comment by nabijaczleweli** [comment]
Released in [`v2.1.0`](https://github.com/thecoshman/http/releases/tag/v2.1.0).
