### ISSUE TITLE
More automation?

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#18]
Can we get stuff like versioning and releasing builds magicked up? What about packaging? I't d be nice to not have to install from source. Signing builds? Automation!

**Comment by nabijaczleweli** [comment]
>versioning

Done manually, because you need to assess the impact.

>releasing builds

Doable, but I prefer to do it manually

>packaging

Done

>not install from source

It's on https://crates.io/crates/https so you install via `cargo install https` and then run via `http <DIR>`

>Signing builds

What?

**Comment by nabijaczleweli** [comment]
How would you feel about enabling AppVeyor for this?

**Comment by thecoshman** [comment]
regarding signing, I mean doing stuff like providing a hashcode of the downloads that we can sign using something like keybase. As for AppVeyor, I've no idea, I'd have to read up about it, but if you think it's worth using then I don't see much reason to not go for it.

Also, testing... not sure what exactly we have covered in the travis builds. Do we have things like validating hte behaviour of symlink following, that it works by default and can be disabled.
