### ISSUE TITLE
Handle DELETE

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#19]
HTTP defines DELETE in [RFC7231](https://tools.ietf.org/html/rfc7231). Support therefor would go a long way towards full write support.

**Comment by thecoshman** [comment]
As a note here... I think this would be good if by default, running this server was side effect free, so DELETEing a file would only flag it in memory that it is deleted so that subsequent requests for that file return a 404.

**Comment by nabijaczleweli** [comment]
You'll see how I handled write on/off when I push.
