### ISSUE TITLE
For directory listings, display information more infomation

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#20]
* [x] last modified date/time
* [x] file size (basic byte count)
* [ ] group/user owner
* [x] indication if 'thing' is directory or file

**Comment by nabijaczleweli** [comment]
I'm not quite sure about ownership because (a) doesn't exist on Windows, (b) isn't in libstd (and couldn't find a crate for it), (c) that's probably irrelevant and leaking information like it is really bad I feel

**Comment by thecoshman** [comment]
Well, if Windows doesn't support, then it can't site it. As for leading info, fair point, it should be an opt-in thing, via another flag. It's not the biggest issue though.
