### ISSUE TITLE
Favicon!

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#23]
I'll probably work on an image for it at some point... just need a default image to make things a bit prettier

**Comment by nabijaczleweli** [comment]
What's the general direction of the favicon?

**Comment by thecoshman** [comment]
What do you mean? It's a basic image file... I'll look to make one, along with other branding stuff when I get back to a proper computer after xmas

**Comment by nabijaczleweli** [comment]
What would you like it to be? I made this beauty:
![fvicn](https://raw.githubusercontent.com/thecoshman/http/develop/assets/favicon.png)

**Comment by thecoshman** [comment]
Not sure what I want... Favicon will probably be done specifically for the tiny size. If you want to go ahead with that for now, grand.
