### ISSUE TITLE
Add short version of --temp-dir option

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#27]
Pulled latest from dev, when running `http -h` the temp-dir is listed as just this... (there should be a `-t` version as well)

> --temp-dir <temp>    Temporary directory. Default: $TEMP

**Comment by nabijaczleweli** [comment]
I preferred it so but if you're sure...

**Comment by thecoshman** [comment]
can you think of anything else `-t` would want to be used for?

**Comment by nabijaczleweli** [comment]
Guess not v0v
