### ISSUE TITLE
Compress generated pages on-the-fly

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#29]
Like #7 but much easier to apply since we have raw strings that we can compress and most of the data we send should compress well.

**Comment by nabijaczleweli** [comment]
Defined in [D.2.1](https://tools.ietf.org/html/rfc1945#appendix-D.2.1) of [RFC1945](https://tools.ietf.org/html/rfc1945) (HTTP/1.0)

**Comment by thecoshman** [comment]
Is this really required for 1.1 compliance? Maybe just handling the request for compression and saying no would suffice? But iirc server offers compression then client scooters like accepts...

**Comment by nabijaczleweli** [comment]
It's *in* `1.1` and I assumed that's what the milestone is for v0v

**Comment by thecoshman** [comment]
Yeah, I think for 1.1 we should support handling compression... But saying there is none I think is valid. But if you can manage something, may as well throw it in

**Comment by nabijaczleweli** [comment]
Closed via  #32
