### ISSUE TITLE
Port scan

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#3]
If the server can't secure the desired port, it should start to increment one at a time until it finds a free port to listen on. This can loop around from max port back to the lowest port that doesn't require privilege escalation. If it loops back to the starting port, it should print an error message and quit

**Comment by nabijaczleweli** [comment]
By default the Rust version uses port `0`, which is a magic number for 
"choose whatever's free", since I couldn't find a good method of checking 
for free ports (now that I think about it, recovering from a server start 
error would prolly work).

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by thecoshman** [comment]
Basically looping until you stop failing to start the server was the main idea I had in my head for how to get this to work. I think that this Rust port `0` would suffice, providing you can print out what port the server is listening on.

**Comment by nabijaczleweli** [comment]
Of course I can (and I do as of `965a0cbcda1810d3ffbac6ff6ddc15cdedc43a4f`), so should we implement this (less clean code-wise, more predictable UX-wise) or leave as-is of `965a0cb` (cleaner code-wise, less predictable UX-wise)?

**Comment by thecoshman** [comment]
For MVP, this would not be required, it's sufficient to just attempt to listen on the hard-coded port or die

**Comment by nabijaczleweli** [comment]
But it is required because it's a part of the implementation already.

**Comment by thecoshman** [comment]
If it's implemented, then fine, close it as done. though thinking wait to close until on master?

**Comment by nabijaczleweli** [comment]
Hover on the magical (i) in top-right of referenced commit line.

Also Katt thinks this is a horrible idea so we might actually want to consider him.

**Comment by nabijaczleweli** [comment]
I'd urge your to consider the argumentation Katt provided in #rust-drama, @thecoshman .

**Comment by thecoshman** [comment]
I might once I've read it :P
what's the summary?
