### ISSUE TITLE
More metadata for log?

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#33]
Like timestamp at least

**Comment by thecoshman** [comment]
You could have things like client ip, if a file is compressed (and then cached) information about what is being uploaded

**Comment by nabijaczleweli** [comment]
We've got client IP in all relevant cases. File's compression/caching status is also there.

> information about what is being uploaded

???

**Comment by thecoshman** [comment]
When people to do a PUT request maybe? Was just throwing out ideas

**Comment by nabijaczleweli** [comment]
```
127.0.0.1:48222 created \\?\P:\Rust\http\index.html, size: 1033554B
```

We log all requests with most of relevant data except time.
