### ISSUE TITLE
Rename executable to `httplz`

### ISSUE THREAD

**Issue by iqualfragile** [thecoshman/http#35]

**Comment by thecoshman** [comment]
Name is done, there's no sense in this new name you suggest.

**Comment by coder543** [comment]
There is lots of sense in `httplz`. Reopen? :)

**Comment by thecoshman** [comment]
There would need to be a very good reason to rename this project and the name of the executable that is currently built. There is nothing at all stopping you from renaming that to suite your own needs. Unless you can provide a objective reason to rename, then please do not drag this out more.

**Comment by nabijaczleweli** [comment]
(We could always add an identical second executable if we get reports of clashes but you heard the man.)

**Comment by messense** [comment]
Current executable name clashes with [`HTTPie`](https://github.com/jakubroztocil/httpie) which is quite popular.

**Comment by thecoshman** [comment]
Yeah, they certainly have a more logical reason to use `http` as the executable name. 

I'm not keen on the name `httplz`, but I can't really think of something better, other than maybe `httpsrv` (as in http server).

I'll open this up for review and to decide on a new name. If people have suggestions for names, please make a simple comment like "name suggestion: httplz" and people can use the thumb up/down for voting for/against. I will make a decision at some point and it may not simply be the one with the most votes.

**Comment by thecoshman** [comment]
Name suggestion: `httplz`

**Comment by thecoshman** [comment]
Name suggestion: `httpsrv`

**Comment by nabijaczleweli** [comment]
Or we could have both `http` and `<othername>` (which would have the added benefit of not breaking/people not using the old execs out of habit).

**Comment by thecoshman** [comment]
I'm inclined to not bother keeping the old name, the point here is that it's clashing with other packages that either more established or have a more logical use for that name.

**Comment by nabijaczleweli** [comment]
Then we'll just have to bump major when we release, NBD

**Comment by thecoshman** [comment]
Oh boy, this old chestnut. So yeah, I finally got around to thinking about this one. I'm happy enough to take on `httplz` as a 'new' name for the binary. For now at least, let's go with the two side by side, but consider the use of `http` deprecated.

**Comment by cyqsimon** [comment]
It would be helpful if this issue is mentioned & linked to in README. I was somewhat confused by why there are two binaries with identical size and help page.

Also if the intention is to deprecate `http`, then I think you should discourage people from using it by making the notice, well, very noticeable.

**Comment by nabijaczleweli** [comment]
It, uh, isn't, really, but I will note the other binary in the README.

**Comment by nabijaczleweli** [comment]
Released in [`v1.11.0`](https://github.com/thecoshman/http/releases/tag/v1.11.0).
