### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#37]
Might be nice if we could also support encryption for this as well.

Would probably have to be done via a cli option to enable and require a path to the required certificate files.  For now, probably just stick to the latest encryption standards, supporting older stuff can maybe done later if felt reasonable

**Comment by thecoshman** [comment]
I guess may as well just use the one cli flag, like "--user-certs <path to cert file>" and that obviously means you want to use https.

**Comment by nabijaczleweli** [comment]
вот
