### ISSUE TITLE
Turn off https redirection 

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#39]
There's potential for the need to run the server with both http and https side by side, and by default http should be redirected to https. A new cli option should be added that will prevent the redirection, I suggest `--no-https-redirect`. Obviously, if https isn't running, this flag would have no effect

**Comment by nabijaczleweli** [comment]
See https://github.com/thecoshman/http/issues/38#issuecomment-281739274

**Comment by nabijaczleweli** [comment]
Closing because https://github.com/thecoshman/http/issues/38#issuecomment-281756303
