### ISSUE TITLE
Colour the log output

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#41]
Nice pretty colours are pretty and nice. Some sort of highlighting should be added. The different elements of the log messages should be highlighted individually. For ease of understand what is going on with the colours, they should be defined in one concise location

**Comment by nabijaczleweli** [comment]
Right, we can pack this alongside #33 and #31 for `1.0.0`.

**Comment by thecoshman** [comment]
I don't see why not. I wouldn't say they have to come together in the same PR, and I don't really care if we blast 1.0.0 with other PR for other things. Also, are you bumping the third version number when doing improvements?

**Comment by nabijaczleweli** [comment]
I bump patch when there's little to no user-facing changes.

**Comment by nabijaczleweli** [comment]
I made this but it's Linux-only (it's a fucking nightmare on Windooze and doesn't work at all), sneak peeks:
![SS1](https://cloud.githubusercontent.com/assets/6709544/21917216/866bf484-d946-11e6-95e3-16f900033b1a.png)
![SS2](https://cloud.githubusercontent.com/assets/6709544/21917224/a0e73260-d946-11e6-8d99-b71f70b4a5ec.png)

Overall, I'd rate this as *very nice*.

**Comment by thecoshman** [comment]
Yeah, colours look nice enough to my eyes. It does highlight that the logging could do with a bit of tweaking, but I'd need to look through the logs more to see how they look

**Comment by thecoshman** [comment]
Are you able to push this up to a feature branch?

**Comment by nabijaczleweli** [comment]
Whoops, that's what I get for not refreshing since yesterday.
Check out the `tweak/41-log-colour` branch for fixups which we'll just squash into develop once they're acceptable.
