### ISSUE TITLE
Blacklist some extensions from being encoded

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#43]
For example things like `zip`s, compressed video files and images, etc. should not be encoded because you're actually losing network and time.

**Comment by thecoshman** [comment]
This makes sense... but I'm not sure how to handle this. Do we only encode when the client requests it, or does the client say what encoding it supports and the server then provides a file using what ever encoding it likes from that list?

**Comment by nabijaczleweli** [comment]
> This makes sense

Good

> I'm not sure how to handle this

I do, so stop worrying.

**Comment by thecoshman** [comment]
I meant form the POV of what RFCs say

**Comment by nabijaczleweli** [comment]
The server is free to do as it pleases WRT respecting `Accept-Encoding`

**Comment by thecoshman** [comment]
oh, well easy peasy then :D

**Comment by NawfelBgh** [comment]
### TODO:

Collect the list of file extensions of:

* All compressed audio formats,
* All compressed video formats,
* All compressed image formats,
* All compressed archive formats.

According to [wikipedia](https://en.wikipedia.org/wiki/List_of_codecs), it looks like all video formats are compressed and almost all audio formats are compressed, [with the exceptions being](https://en.wikipedia.org/wiki/List_of_codecs#Non-compression):

> #### Non-compression
>
> * Linear Pulse Code Modulation (LPCM, generally only described as PCM) is the format for uncompressed audio in media files and it is also the standard for CD-DA; note that in computers, LPCM is usually stored in container formats such as WAV, AIFF, or AU, or as raw audio format, although not technically necessary.
>   * FFmpeg
> * Pulse-density modulation (PDM)
>    * Direct Stream Digital (DSD) is standard for Super Audio CD
>        * foobar2000 Super Audio CD Decoder (based on MPEG-4 DST reference decoder)
>        * FFmpeg (based on dsd2pcm)
> * Pulse-amplitude modulation (PAM)

**Comment by nabijaczleweli** [comment]
I've already done most: https://github.com/thecoshman/http/blob/63e7f54c8388370fe29ce54a93ac97e6db5e0f3a/assets/encoding_blacklist
