### ISSUE TITLE
Parent directory links always point to root

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#45]
While their `href` is `../`, the link hint points to server root, and, indeed, it takes you there.
I'm on Firefox DevEdition Latest so it might just be it, or it might not. We need to confirm with more browsers.

**Comment by thecoshman** [comment]
Confirmed in Chromium

**Comment by nabijaczleweli** [comment]
Extraordinary

**Comment by thecoshman** [comment]
Point is, I would say it's a bug in the way you are parsing the links, you could maybe get away with generating absolute paths for parent directory, but that will still not solve the issue if a user provided file uses such a path.

Might also be worth trying it with a user provided file that uses relative path for links to an image.

**Comment by nabijaczleweli** [comment]
What user provided file are you on about exactly?

**Comment by thecoshman** [comment]
let's say I host a folder with `/demo/js_stuff/power.js`.

I should be able to 'get' a file `/demo/html/example/index.html` (without having to explicitly say `index.html`, but that's not the concern here) and in that html file I should be able to reference the js file both with the absolute path, as above, but aslo by saying `../../js_stuff/power.js`.

I've not tested this sort of thing, but based on how the dir listing works, I suspect this will incorrectly attempt to serve me `/js_stuff/power.js` which of course it will not find, and thus give me a 404.

**Comment by nabijaczleweli** [comment]
That work
