### ISSUE TITLE
Installers

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#46]
I can generate an `curl | sh`-kind installer for Linux and a normal one for Windooze on respective CIs.

**Comment by thecoshman** [comment]
I wouldn't mind seeing .deb packages and the likes. What did you have in mind for a `curl | sh` script? 

I think we can look to use a github site to host packages for download... not sure what exactly is required to make a repository that people can pull from. I'm thinking things like a ppa.

**Comment by nabijaczleweli** [comment]
> seeing .deb packages 

I've no earthly idea how `.deb`s work, is there a thing that makes them?

> mind for a curl | sh script

The usual `curl https://raw.githubusercontent.com/thecoshman/http/master/install.sh | sh`.

> use a github site to host 

GitHub Releases

> things like a ppa

I've no idea how they work (yet).
