### ISSUE TITLE
Improve the UI of folder listings.

### ISSUE THREAD

**Issue by NawfelBgh** [thecoshman/http#47]
The served pages for directory listings don't look good (especially in mobile)

* In mobile:
  * I need to both "zoom in" and "scroll" left and right which is not a very nice experience.
  * I need to click exactly on the link to send a request. This is especially hard on mobile. I mean: I'm used in many file managers to the behaviour of something similar to  `<a><div>Name, Last modified, Size</div></a>` so that I can click anywhere in the box containing the file name to trigger a request.
* Both in desktop and mobile:
  * There is no way to change the sort order.

Google Drive is a good example of a professional-looking web-based file-browser. If you are using a desktop browser you get something like this:

![drive](http://weborb.gcflearnfree.org/weborbassets/uploads/ID_77/2015_background.png)

And with a mobile phone you get (This can be accessed by using responsive mode in firefox and setting the user agent to: `Mozilla/5.0 (Android 4.4; Mobile; rv:50.0) Gecko/50.0 Firefox/50.0`):

![screenshot from 2017-01-24 10-50-59](https://cloud.githubusercontent.com/assets/1393737/22242836/20c4e842-e225-11e6-8063-7a31dea28d99.png)

and 

![screenshot from 2017-01-24 10-51-25](https://cloud.githubusercontent.com/assets/1393737/22242917/86604a98-e225-11e6-8fd8-191a9703f3a9.png)

--------------------------------------------------------

## Let's define the goals of this project

I think that it is good to write down:

* **The functional specification**: How exactly the served webpages are supposed to behave both on desktop and mobile. For example, I wouldn't suggest to replicate every feature of Google Drive but let's decide on which features we like to support.
* **The technical specification**: For example, serving a simple web page (usable by old browsers) but progressively enhanced by `flexbox`.

**Comment by thecoshman** [comment]
The intention is mostly that the server be light weight and quick to start. That I said, I do agree that we could do with improving the web pages that are generated. Things like making the links targets larger than just the text are a good usability thing. 

I will take some time to improve the UI that is generated, especially as we now have a good bit of raw functionality available. I know for once thing really need to provide a decent way to upload files.

**Comment by nabijaczleweli** [comment]
> really need to provide a decent 

Excuuuuuse meeeeeeeee there's Drag&Drop

**Comment by NawfelBgh** [comment]
> there's Drag&Drop

@nabijaczleweli I think that adding a more visible button is a good idea.

**Comment by nabijaczleweli** [comment]
@thecoshman Confirm and open issue if so.

**Comment by thecoshman** [comment]
There's a range of things that need to be done for improving the UI. And yes, a drag and drop is nice, but there is nothing in the UI to even suggest you can use it. I'll create tickets and work on the UI side of things soon.

**Comment by thecoshman** [comment]
I believe we currently have tickets created for all the individual parts of improving the UX, if not feel free to either suggest them here or preferably just create a ticket for the idea.
