### ISSUE TITLE
Use a normal html file upload as well

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#49]
Drag and drop is all well and good, but isn't clear. A form thing should be added to the directory listing pages which allows people to select a file and then upload them to the current folder. 

Initially this can just upload one file at a time, but it can be 'upgraded' as per browser support so that you can upload multiple files and/or upload without requiring page refresh.

**Comment by nabijaczleweli** [comment]
Where would it lie? After another `hr` in the footer? At a fixed position in the top-right?

**Comment by thecoshman** [comment]
I don't think a fixed position thing would be good, it should either be at the top or bottom. I'd probably be more inclined to say at the top to be fair.

**Comment by nabijaczleweli** [comment]
I put it at the bottom for now because I'd no idea where to put it at the top.

**Comment by thecoshman** [comment]
ha ha ha, well yeah,I was planning to do this UI stuff myself, but I've been caught up with other stuff ¬_¬

**Comment by nabijaczleweli** [comment]
So where specifically is it to go, then?

**Comment by thecoshman** [comment]
bottom is fine, at least it's on there
