### ISSUE TITLE
Scale the UI for Mobile

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#51]
When going down to physically smaller screens, the UI should adapt so that it is still nice looking.

yay for fluffy non precise issues :D

**Comment by nabijaczleweli** [comment]
Agreed-on baseline: https://github.com/thecoshman/http/issues/50#issuecomment-275810179

**Comment by nabijaczleweli** [comment]
Mobile UI looks like this (`feature/51-mobile-UI-scale` branch):

![SS](https://cloud.githubusercontent.com/assets/6709544/22470081/65adcef2-e7ce-11e6-831b-328fa8ccc585.png)

**Comment by nabijaczleweli** [comment]
Mobile UI looks like this (`feature/51-mobile-UI-scale` branch):

![SS](https://cloud.githubusercontent.com/assets/6709544/22470081/65adcef2-e7ce-11e6-831b-328fa8ccc585.png)

@NawfelBgh -- based this on GH's mobile layout but I appreciate your nitpicks

**Comment by NawfelBgh** [comment]
Nice to see this issue addressed 👍.

The text is still small. I still need to zoom and scroll right & left in my device.

This is what I get in my phone (4.0" 480x800 pixels, css pixel ration: 1.5) as of commit 1a8148f3eba27df01c104c3b5baff5481af8edf9:

![screenshot_2017-01-31-17-29-00](https://cloud.githubusercontent.com/assets/1393737/22473995/efb2fae4-e7da-11e6-904e-052e5d84900d.png)

Device Info:

![screenshot_2017-01-31-17-55-16](https://cloud.githubusercontent.com/assets/1393737/22475741/35d4e24e-e7e0-11e6-99c9-af42d1103fea.png)


and here is github in the same phone:

![screenshot_2017-01-31-17-31-48](https://cloud.githubusercontent.com/assets/1393737/22474066/3496778a-e7db-11e6-817c-ff1b1ab20370.png)

## Note

Note that I can't zoom in and out the github page in my phone. It always stays the same size. When inspecting its html in responsive design mode, i found these tags in the `<head>`:

```html
<meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width">
<meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)">
````

**Comment by nabijaczleweli** [comment]
Ya I noticed the scaling issue

**Comment by NawfelBgh** [comment]
Upon  adding the 2 lines to `assets/directory_listing_mobile.html`, I got:

![screenshot_2017-01-31-18-16-53](https://cloud.githubusercontent.com/assets/1393737/22476163/a062c0f8-e7e1-11e6-88db-e221590bc829.png)

with same no-zoom behavior as github.

**Comment by NawfelBgh** [comment]
```diff
diff --git a/assets/directory_listing_mobile.html b/assets/directory_listing_mobile.html
index abfacb2..4791a61 100644
--- a/assets/directory_listing_mobile.html
+++ b/assets/directory_listing_mobile.html
@@ -1,6 +1,8 @@
 <!DOCTYPE html>
 <html lang="en">
   <head>
+    <meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width">
+    <meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)">
     <meta charset="utf-8">
     <meta name="application-name" content="http">
     <meta name="author" content="http developers">

```

**Comment by nabijaczleweli** [comment]
Hmm, Katt said "Don't set user-scalable unless you have a special thing (like you do your own zooming because it's a LOD map or something)" so I didn't and it still works.

So ya, re-pull and re-check

**Comment by NawfelBgh** [comment]
I don't know if this is a caching issue, but I get:

```shell
$ git pull origin feature/51-mobile-UI-scale 
From https://github.com/thecoshman/http
 * branch            feature/51-mobile-UI-scale -> FETCH_HEAD
Already up-to-date.

```

**Comment by nabijaczleweli** [comment]
Ah yes, seems I made a typo. Should be up now

**Comment by NawfelBgh** [comment]
Sorry I removed my comment out of confusion. I got 679b1a83a500ae now but it doesn't compile.

**Comment by nabijaczleweli** [comment]
Of course it doesn't, that's what I get for pushing without compiling :v

I fixed things and checked that they compile so maybe test now?

**Comment by NawfelBgh** [comment]
Splendid! 🎉  It works perfectly now... except for this little bug that I just discovered 😛:
When you have a file name where words are separated by underscores, the mobile ui lets you scroll vertically in weird fashion.

![screen shot 2017-01-31 at 18 58 28](https://cloud.githubusercontent.com/assets/1393737/22477693/50f2e5ec-e7e7-11e6-988e-36b8a0f5b3f0.png)

**Comment by nabijaczleweli** [comment]
Fixed: ![SS](https://cloud.githubusercontent.com/assets/6709544/22480169/baa8fe00-e7f0-11e6-9f82-e8790dd80c6d.png)

**Comment by nabijaczleweli** [comment]
Alright, big question time: is this ready to roll or what?

**Comment by NawfelBgh** [comment]
Yes. I think that the `feature/51-mobile-UI-scale` branch addresses the issue very well.
