### ISSUE TITLE
Support uploading directories

### ISSUE THREAD

**Issue by NawfelBgh** [thecoshman/http#53]
When I upload a directory using the current version, a 0 byte file is created and a no error is shown.

I expect either:
* getting an error (unimplemented feature) or
* that the feature works.

I tried uploading a directory to Google Drive with drag and drop on Firefox 50.0 and it worked correctly. Firefox 50.0 [is the first firefox release to support this](https://developer.mozilla.org/en-US/Firefox/Releases/50#Files_and_directories) but chrome always did.

As to how to implement this feature, it is described here: https://wicg.github.io/directory-upload/proposal.html

**Comment by nabijaczleweli** [comment]
> that the feature works.

Well, it does *now*.

**Comment by NawfelBgh** [comment]
I tested and confirmed. Good job 👍

**Comment by nabijaczleweli** [comment]
I didn't fuck something up for once! Magnificent.
