### ISSUE TITLE
Add icon to executable on Windows

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#54]
It's simple enough to do (I have ready-to-go `build.rs`es from my other projects I can just plug in), just wondering if we *should*.

**Comment by thecoshman** [comment]
I don't see why not. At some point I think the overall aesthetics will want to be reviewed, but no harm putting in something now, even if it is just a place holder. Should look to see about this on other platforms I'd say.

**Comment by nabijaczleweli** [comment]
> other platforms

Linux doesn't have anything consistent (surprise, surprise) and GSearch for doing this on Mac yielded naught.

**Comment by thecoshman** [comment]
I think for Linux there would be a standard X11 way of doing an application icon, and then maybe different window managers have their own ideas about doing things. I'd say supporting 'standard' X11 and then gnome and kde would be a good enough start... but that might be getting a bit too tedious.

**Comment by nabijaczleweli** [comment]
I dug a little more and there seems to be no standard X11 way of doing this, just Gnome/KDE, which require external files (we can't deploy them "normally", but I could make the installer do so, I think).

**Comment by nabijaczleweli** [comment]
(nota bene: closed in 98205a4096e5535dfb0075b066c051ad27a92e9f)

**Comment by thecoshman** [comment]
Right so, let's just use this ticket for Windows Icon, if someone really wants icons for other desktops, they can open tickets specifically for them.
