### ISSUE TITLE
Last modification time is shown in GMT+0 which is confusing

### ISSUE THREAD

**Issue by NawfelBgh** [thecoshman/http#56]
Currently, last modification time is always displayed in GMT+0 which is a little confusing. I think that we should either:

* Write "xx-xx-xx xx:xx:xx **(GMT)**" to clarify, or
* Display time in the timezone of the client.

**Comment by nabijaczleweli** [comment]
It's not (or, well, shouldn't) be UTC, it's the server's TZ.

Since we don't have access to the client's TZ we'll just specify UTC.

**Comment by nabijaczleweli** [comment]
Surprisingly enough, it seems that both what's supposed to be server TZ and UTC return UTC, so UTC it is

**Comment by NawfelBgh** [comment]
> both what's supposed to be server TZ and UTC return UTC

Can't we get the server time zone in the rust side?

**Comment by nabijaczleweli** [comment]
Well it returns UTC (and I'm not in UTC) so might as well prevent confusion.

**Comment by NawfelBgh** [comment]
The chrono crate can convert to local time (server's tz): https://lifthrasiir.github.io/rust-chrono/chrono/offset/local/struct.Local.html

> `fn from_utc_datetime(&self, utc: &NaiveDateTime) -> DateTime<Self>`
>
>Converts the UTC NaiveDateTime to the local time. The UTC is continuous and thus this cannot fail (but can give the duplicate local time).

**Comment by nabijaczleweli** [comment]
Yeah, but this is more open-ended. Plus, I can do a JS thingamajig to adjust to local TZ, which sounds like a good idea.

**Comment by NawfelBgh** [comment]
I'm OK with both approaches: chrono and js-adjustment.

**Comment by nabijaczleweli** [comment]
See referenced commit for fix

**Comment by NawfelBgh** [comment]
I tested the the feature. It works on firefox 51.0.

**Comment by thecoshman** [comment]
I'm not sure what is best when it comes to reporting time stamps... UTC is probably the best option. But would require us to parse what ever we get back from file system, but I also think that maybe we should just report whatever the file system reports... too many options!

**Comment by nabijaczleweli** [comment]
(a) this is already done, (b) what we get from the FS is a delta
