### ISSUE TITLE
Temp directory for uploads isn't removed

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#58]
If I start the sever with write support, and upload some files/folders, then restart the server, I am still able to access the resources that I uploaded to the temp location. These should have been removed as part of the server shutdown process.

I believe that we can intercept the ctrl-c action so that we could have time to remove the temp folder, though other interrupts might kill our process before we get chance to clean up, but that's not normal shut down procedure.

**Comment by nabijaczleweli** [comment]
Yeah, well, intercepting Ctrl-C *can* be done and I've tried it at least twice, but it doesn't *quite* work because it first hogs the CPU, then just crashes outright without reaching the destructor. (That's a `hyper` bug I can do naught about).

**Comment by thecoshman** [comment]
Can we perhaps look to have another way of exiting the cli, one that we control and allows us to stop listening, clean up and exit cleanly?

**Comment by nabijaczleweli** [comment]
Okay, there were some API updates between `v1.0.0` when I tried it and now and it *does* work now.
