### ISSUE TITLE
Create temp shadow folder for writing to

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#6]
Running http should not come with the risk of you losing any data, and so the folder that it servers should be considered read-only.

However, to support methods such as POST, the server will need a place to write files to. By default a 'randomly' named folder should be created anywhere in the OS (ie /tmp/<random id> ). This folder should then be deleted afterwards.

This folder should only be created when it is first required.

**Comment by nabijaczleweli** [comment]
Nota bene: the folder isn't deleted on shutdown because in newest https://crates.io version of `hyper` `Listening::close()` is buggy and after calling it the CPU usage soars to 100% for a couple of seconds then the program silently crashes without calling destructors.

**Comment by thecoshman** [comment]
... anything to be said for not using the latest version? seems like a simple solution to me?

**Comment by nabijaczleweli** [comment]
No because in this case "the latest version" means "everything thereupto"
