### ISSUE TITLE
Links to files with # in the names broken in dir listing

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#60]
Since it's interpreted as a `ref`link.

**Comment by nabijaczleweli** [comment]
`#`s can be escaped as `%23`, question is: are there any other "speszol" characters?

**Comment by thecoshman** [comment]
I think there would be a fair few special characters that can be encoded... but I'm not sure what ones have to be encoded. Either way, shouldn't be too hard to have a look up table to this. Probably could look to make a new library the specialises on just URL encoding the links. I'd do it myself, but I'm just too lazy
