### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#61]
After D'Oh's RFSAPI, so two versions from now, but definitely a thing to consider.

Breaking it up would probably be a good idea too

[Ref](http://webdav.org)

**Comment by thecoshman** [comment]
Yeah, sure. Why not make this thing even more over powered than it needs to be. As you say, probably worth trying to break it down into smaller features... but I guess you either support WebDAV or not. Unless there is like some core/minimal version to support and then further support can be added later.

**Comment by nabijaczleweli** [comment]
Got about as far as [`webdav` branch](https://github.com/thecoshman/http/tree/webdav) and then I read the spec and other implementations and realised WebDAV is an XML abomination.

If someone wants to PR it in in a way that isn't thrice as big as the existing codebase, though, I'm all for't.

**Comment by thecoshman** [comment]
Yeah, having taken the time to look into WebDAV it honestly seems like a waste of time, that said, if someone is insane to implement this in a decent way... I'm fairly sure we can accept a PR on it.

**Comment by nabijaczleweli** [comment]
xD https://twitter.com/interruptinuse/status/1169591404198322177

**Comment by nabijaczleweli** [comment]
Currently done on `webdav` branch

**Comment by nabijaczleweli** [comment]
Released in [`v1.8.0`](https://github.com/thecoshman/http/releases/tag/v1.8.0)
