### ISSUE TITLE
Funky interaction between DELETE and dir symlinks

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#62]
Looked like it resolved then deleted recursively, probably needs a speszolcase to just unlink.

**Comment by thecoshman** [comment]
Yeah, generally speaking, if the client asks to delete a folder that is actually just a symlink, we should only delete the link.

**Comment by nabijaczleweli** [comment]
This is fixed in *the* PR, which you'd've noticed if you paid attention.

**Comment by thecoshman** [comment]
Yeah, I asked before I read that :P Just seems a bit odd to report a bug on code that is only in a PR... I wouldn't really consider that a bug, but what ever.

**Comment by nabijaczleweli** [comment]
fam, the bug is ever since that function was added, which is https://github.com/thecoshman/http/commit/e9a62f879bf01e7a87b97f97e8ac0e17e19f9a7e, the fix is in the PR
