### ISSUE TITLE
Failed to install on Mac OS X

### ISSUE THREAD

**Issue by varkor** [thecoshman/http#69]
When I try to run `cargo install http`, I get the following:
```
tl.c:2:10: fatal error: 'linux/fs.h' file not found
cargo:warning=#include <linux/fs.h>
cargo:warning=         ^
cargo:warning=1 error generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-E" "/var/folders/5_/hmrg04kx24b3q_wjr6q7v5tm0000gn/T/cargo-installoZX3fX/release/build/https-42fae33222fd6a00/out/ioctl-data/ioctl.c" with args "cc" did not execute successfully (status code exit code: 1).

'
```
Presumably because `<linux/fs.h>` is incorrect for Mac OS X.

**Comment by nabijaczleweli** [comment]
Can you check if [current `develop`](https://github.com/thecoshman/http/commit/e022f4c168a14847b33b7d6179ad8dcf1d995d40) works for you?

**Comment by varkor** [comment]
@nabijaczleweli: no, it doesn't. I think the issue is that `not(target_os = "osx")` should be `not(target_os = "macos")`. If I change that, it gets further, though it then seems to hit another error:
```
error: couldn't read ".../http-develop/target/debug/build/https-e56612e49525e6f9/out/ioctl-data/ioctl.rs": No such file or directory (os error 2)
 --> src/util/os/non_windows.rs:9:1
  |
9 | include!(concat!(env!("OUT_DIR"), "/ioctl-data/ioctl.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by nabijaczleweli** [comment]
Yes, I was not quite sure what to make the condition there :v
Anyway, updated `develop` to check for the Windows/MacOS case better, care to check it?

**Comment by varkor** [comment]
Now I hit the error:
```
error[E0425]: cannot find function `get_ioctl_data` in this scope
  --> build.rs:33:5
   |
33 |     get_ioctl_data();
   |     ^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error
```

**Comment by nabijaczleweli** [comment]
Oh god, it seems like I've missed the `"osx"` at line 40 in `build.rs`. Terribly sorry, but would you mind replacing that with `"macos"` and trying again?

**Comment by ckampfe** [comment]
I was able to build a release on `develop` by changing `osx` to `macos` on line 40 in `build.rs` 😄
