### ISSUE TITLE
Compress requested data on-the-fly

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#7]
Time-wise CPU&RAM is cheap, network is not. We can do magic and send compressed data via Encoding header.

**Comment by thecoshman** [comment]
If I am not mistaken, this is a covered via an RFC. I would also consider this a low priority thing, this would be intended for use over LAN, probably local host most of the time, so not much need to worry about network.

**Comment by nabijaczleweli** [comment]
`Accept` header defined in [D.2.1](https://tools.ietf.org/html/rfc1945#appendix-D.2.1) of [RFC1945](https://tools.ietf.org/html/rfc1945) (HTTP/1.0)
