### ISSUE TITLE
PUT allows file PUTting behind symlinks even with symlinks turned off

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#72]

**Comment by nabijaczleweli** [comment]
No, with symlinks *on* everything behaves as expected.

With symlinks *off*, though, you could still PUT things behind them, since it was unchecked; the current behaviour is to return a 404 like the rest of invalid accesses.

**Comment by thecoshman** [comment]
So currently, if symlinks are not enabled, attempting to GET/PUT to a location that is actually symlink simply returns a 404 error?

For GET, that would be correct. But for PUT, it should work, storing/updating a file in a temp location, agreed?

I see you've already committed something around this, what does this change?

**Comment by nabijaczleweli** [comment]
[The relevant portion](https://github.com/thecoshman/http/commit/02a8ac091a4c2389524666b2996140bc6971bee0#diff-bcc2b8e33d1d11d5142549cfc9d67006R722) of that commit implements 404ing, but that's non-definitive and I just noticed it when I was going through every verb. I'll change that to dump to temp, though, good call.
