### ISSUE TITLE
Update my email

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#74]
Noticed that my @gmail is being used here, so I'll be looking to update that at some point.

I'll have to workout what email I actually to use, it's a big deal like.

**Comment by thecoshman** [comment]
`http@thecoshman.com` seems ok... but maybe I'll go with a more generic one... I think I'll pick `rust@thecoshman.com` 👍

**Comment by nabijaczleweli** [comment]
Released in [`v1.4.1`](https://github.com/thecoshman/http/releases/tag/v1.4.1).
