### ISSUE TITLE
How to connect JS/CSS files to my index.html

### ISSUE THREAD

**Issue by hajsf** [thecoshman/http#80]
In the my app folder I've subfolder containing my `JavaScript` files, the pat of full path of these files is:
`app/openui5-runtime-1.61.2/resources/sap-ui-core.js"'`

so, in the `index.html` file, I tried calling this `js` file as:
`src='./openui5-runtime-1.61.2/resources/sap-ui-core.js"'`

But got the below error:

> GET http://localhost:8000/openui5-runtime-1.61.2/resources/sap-ui-core.js%22 net::ERR_ABORTED 404 (Not Found)

Whats the way to link the JS/css files correctly?

Thanks

**Comment by nabijaczleweli** [comment]
Well, assuming your `index.html` resides at root, and your JS in `/app/openui5-runtime-1.61.2/resources/sap-ui-core.js` then it's probably by using that exact string :Р

**Comment by thecoshman** [comment]
If you just have you own `index.html` and ` Javascript file, you should be able to test that you have the correct `src` path by just opening the html file in a browser. 

It looks like in this case, you are not using the correct relative paths. 

I'm going to close this, as it's not a question about http itself, but rather a general question about html and js.
