### ISSUE TITLE
Installing with "cargo install" fails on Ubuntu

### ISSUE THREAD

**Issue by Apromixately** [thecoshman/http#85]
`cargo install https` on Ubuntu gives me a 

```
error: failed to run custom build command for `openssl v0.9.24`                                     
process didn't exit successfully: `/tmp/cargo-installbaFa52/release/build/openssl-28365257436483ab/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/zelda/.cargo/registry/src/github.
com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by nabijaczleweli** [comment]
Install OpenSSL (via `apt install openssl` or otherwise) and try again?

**Comment by Apromixately** [comment]
@nabijaczleweli Both libssl-dev and pkg-config are installed, yeah.

**Comment by Apromixately** [comment]
This is Ubuntu 19.04 with libssl-dev 1.1.1b-1ubuntu2 and pkg-config 0.29.1-0ubuntu2 in case that helps.

**Comment by nabijaczleweli** [comment]
Okay, so: `iron` 0.6.0 ends up pinning `openssl` to 0.9.24 down the line and I haven't been able to force it to use something fresher (fun fact: OpenSSL 1.1.1 support was added in Feb 2018 with https://github.com/sfackler/rust-openssl/commit/276577553501164c183ebffa2accf87380dac8c0, and I hate software), and it doesn't look like they're pushing anything new to Crates.io anytime soon, so :v

*However*, what you *could* do, and what should work is to open `/home/zelda/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs` and replace 

```rust
        _ => panic!("Unable to detect OpenSSL version"),
```

on line 16 with 

```rust
        _ => println!("cargo:rustc-cfg=ossl110");
```

Which will make `openssl` build to target OpenSSL 1.1.0, which OpenSSL 1.1.1 should be API(ABI?)-compatible with.

**Comment by Apromixately** [comment]
I'm just going to agree with the "I hate software" statement.

**Comment by pickfire** [comment]
The same goes for Arch Linux, the `hyper-native-tls` crate is probably too old.

**Comment by nabijaczleweli** [comment]
I mean, essentially, yeah. `iron` hasn't released since `0.6.0` *2 years* ago, pins `hyper-native-tls` at `0.2` and therefore `openssl` at `0.9`, and I haven't found a reliable way of forcing it to use a newer version of either through `cargo` and friends – the best I found was to apply the patch mentioned above, as based on analysing the `openssl` repo, so I don't think there's anything I can do to alleviate this. Sorry!

**Comment by thecoshman** [comment]
ergh... is it worth looking to fork `iron` simply to keep it updated?

**Comment by nabijaczleweli** [comment]
No for a multitude of reasons. Not the least of which is that you wouldn't be able to publish it anyway.

**Comment by thecoshman** [comment]
Well obviously we can't publish it as `iron`, but yeah... probably not worth the effort of trying to maintain a fork.

**Comment by pickfire** [comment]
Maybe `iron` can pass own the maintainership?

**Comment by thecoshman** [comment]
This is also getting a bit off topic here. If you want to, raise the question of ownership on their project. I don't really have the knowledge or time to develop it, but I would be willing to take on the caretaker role.

As for this issue, I guess it's basically at a stalemate. Either you follow the advice from @nabijaczleweli and hack the build, or you look to have `iron` update.

**Comment by nabijaczleweli** [comment]
> pass the maintainership

You do realise that iron is under active development, right?

In related news, I found https://github.com/iron/iron/issues/584, which means I can probably PR this in.

**Comment by nabijaczleweli** [comment]
Update: the PR has been merged, if you reinstall `http`, the issue should be resolved by default!

**Comment by nycex** [comment]
Do you mean `https`? Because that still doesn't work for me.

**Comment by nabijaczleweli** [comment]
The package name is still `https`. what's the error?

**Comment by nycex** [comment]
Basically the same as OP I think
```
error: failed to run custom build command for `openssl v0.9.24`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installxEIc3f/release/build/openssl-3491c6dc184890dc/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `https v1.5.0`, intermediate artifacts can be found at `/tmp/cargo-installxEIc3f`
```

**Comment by nabijaczleweli** [comment]
Ah yeah, you're right, I forgot I had to update our `hyper-native-tls` dep, too. I pushed 1.5.1 to Crates, which should actually remove all dependencies on older `openssl`s, so I'd be grateful if you could try again now

**Comment by nycex** [comment]
Yes, installing works now
