### ISSUE TITLE
`--gen-ssl` do not work on MacOS

### ISSUE THREAD

**Issue by non-descriptive** [thecoshman/http#86]
Mac OS 10.15 Beta 
http 1.5.0

```bash
$ http --gen-ssl
Opening TLS certificate failed.
```
Does it require some perquisites to do generating and signing?

**Comment by nabijaczleweli** [comment]
Well, yes, it does require `openssl`, but if you got to opening the cert, then that's not it.

Can you try running `http --gen-ssl --temp-dir .` and check back with the contents of `./{slug}/tls/`?

**Comment by non-descriptive** [comment]
It's created `tls.crt`, `tls.key` and `tls.p12` non-empty files. Attempt to pass `.p12` or `.key` to `--ssl` display the same 'Opening TLS certificate failed`. Passing `.crt` panics with 
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: native_tls::imp::Pkcs12::from_der
  10: native_tls::Pkcs12::from_der
  11: hyper_native_tls::NativeTlsServer::new
  12: http::ops::try_ports
  13: http::actual_main
  14: http::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
```
which probably make sense because I pass wrong file (not really familiar with ssl keys).

**Comment by nabijaczleweli** [comment]
Hmm... Theoretically, passing the `.p12` file to `--ssl` should work.

Could you (a) try running `http --ssl tls/tls.p12` on this attachment: [tls.zip](https://github.com/thecoshman/http/files/3396686/tls.zip).

And could you post the key pack your `http` generates? I'm starting to think your `openssl` version/build generates incompatible keys

**Comment by non-descriptive** [comment]
Attempt to open tls key from your pack ends with the same `Opening TLS certificate failed.`. 
Generated keys:  [tls.zip](https://github.com/thecoshman/http/files/3397346/tls.zip)

i think there's a chance it's an issue with new MacOS Beta update. It did some nasty stuff about access  permissions to files (like with [docker](https://github.com/docker/for-mac/issues/3698), I have this issue too).

**Comment by nabijaczleweli** [comment]
Your certificate opens just fine on my machine so :v

Did you try running `http --gen-ssl` as root? If that works, that'd definitely confirm that this is the same issue as that docker one

**Comment by non-descriptive** [comment]
Running as root display same error. I will try `first aid` option later and let you know if it will fix anything.

**Comment by non-descriptive** [comment]
So, I tried first aid and it fixed docker but not httplz. Still fails the same way. Is there any suggestion how can i check why exactly it fails? It's emmitted [here](https://github.com/thecoshman/http/blob/ab89d02aadaf530593719c4bf2c86ae9ac71bbb9/src/ops.rs#L1090) I tnink, but don't know how to check what exactly went wrong.

**Comment by non-descriptive** [comment]
Probably it is an issue with outdated `hyper` v10.x crate, which `iron` based upon. It's removed some [API](https://github.com/hyperium/hyper/issues/1218) (v11.x) and suggest to use `hyper-tls` and a `hyper-tls-native` some backport compatibility thing for hyper 10.x. Could it be the case?

**Comment by nabijaczleweli** [comment]
You could replace this line

```rust
try!(NativeTlsServer::new(id, pw).map_err(|_| {
```

with

```rust
try!(NativeTlsServer::new(id, pw).map_err(|e| { eprintln!("{}", e);
```

to see the specific error.

As for openssl: yeah, it's a Problem and I wouldn't be surprised, but I couldn't find any way to override the `hyper` &a. versions (see #85).
For now, the whole stack is pinned down by `iron`, at least until [my fix PR](https://github.com/iron/iron/pull/612) is merged, sadly

**Comment by non-descriptive** [comment]
`eprintl` yielded 
```
error initializing acceptor: MAC verification failed during PKCS12 import (wrong password?)
Opening TLS certificate failed.
```
And it's also probably some [issue](https://discussions.apple.com/thread/3630009) with macOS distribution. Is there a way to generate and use some password/passphrase for generated key? If not, I think we can close this question as dupe of #85.

**Comment by nabijaczleweli** [comment]
There's not, short of generating the key manually.

Alright, then, closing in favour of #85.

**Comment by nabijaczleweli** [comment]
Update: the PR has been merged, if you reinstall `http`, the issue should be resolved by default!

**Comment by non-descriptive** [comment]
Tested on 8189d6a. Same error with PKCS12 import.

**Comment by nabijaczleweli** [comment]
Well fuck

**Comment by nabijaczleweli** [comment]
@non-descriptive can you try current `develop` branch (at least 112905b1f5b8c6123995cc67590ab27bfc1f957d)?

Works on a VM on what identifies itself as `Darwin nabs-iMac-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64`, but, well

**Comment by non-descriptive** [comment]
Initial command kinda works
```
$ http --gen-ssl
Hosting "." on port 8000 with TLS certificate from "$TEMP/somefolder/tls/tls.p12" and no authentication...
Ctrl-C to stop.
```
It start to host on `localhost:8000`, but page is unreachable from chrome due to `NET::ERR_CERT_INVALID`. it's probably works in firefox, because it allows to skip this error.
1. so there's soundness issue, because `"."` is not a valid web address and `localhost` or `127.0.0.1` isn't displayed. Maybe it's a good idea to format it something like
```
folder: /Users/user/full/path/to/folder
address: localhost: 8000
tls cert: $TEMP/path/cert
auth: yes/no
```
2. certificate exist but invalid

Also tested passing `-a` and `-p` params.
```
$ http -a 127.0.0.1  --gen-ssl
Hosting "." on port 8000 under address 127.0.0.1 with TLS certificate from "$TEMP/somefolder/tls/tls.p12" and no authentication...
Ctrl-C to stop.
```
works as previous, but with `-p`
```
$ http -a 127.0.0.1 -p 8080 --gen-ssl
Opening TLS certificate failed: error reading identity: No such file or directory (os error 2).
```

**Comment by nabijaczleweli** [comment]
Cool, good to know!

The output's correct, because it's listening on port 8000, unbounded by destination address (you'd conventionally denote this "0.0.0.0:8000", I guess).

2. was a long-standing bug, introduced in the initial TLS implementation (f0bba3dcac8b240960e00606a4e459167f68b609) in 2017! Though it could only surface after --gen-ssl. Thanks for the report!
