### ISSUE TITLE
Delete, Rename and New Folder Buttons

### ISSUE THREAD

**Issue by elliotpotts** [thecoshman/http#93]
It would be nice to be able to delete and rename entries in addition to being able to make new folders.

Edit: It would also be nice if I could select multiple entries and delete/move them. I guess this feature request amounts to asking for full file manager functionality.

**Comment by nabijaczleweli** [comment]
Sure, but scheduled after #91 then #61

**Comment by nabijaczleweli** [comment]
With https://github.com/thecoshman/http/commit/b71eabc25c40c5ee17752a1c6f991e5caf01cde8 this is feature-complete.

Desktop:
`http -wd`: ![-wd](https://user-images.githubusercontent.com/6709544/68152418-e9af9200-ff43-11e9-9b0b-6639ea4f0858.png)
`http -w`: ![-w](https://user-images.githubusercontent.com/6709544/68152458-fd5af880-ff43-11e9-990a-a8f1eaa797b7.png)
`http`: ![none](https://user-images.githubusercontent.com/6709544/68152487-0c41ab00-ff44-11e9-9c4a-a3cc7acc07a9.png)

Mobile:
`http -wd`: ![Screen Shot 2019-11-04 at 20 54 15-fullpage](https://user-images.githubusercontent.com/6709544/68153157-59724c80-ff45-11e9-80b7-c1dc8fb3de24.png)
`http -w`: ![Screen Shot 2019-11-04 at 20 56 10-fullpage](https://user-images.githubusercontent.com/6709544/68153320-92aabc80-ff45-11e9-811a-9eb01b039a98.png)
`http`: ![Screen Shot 2019-11-04 at 20 56 44-fullpage](https://user-images.githubusercontent.com/6709544/68153388-a35b3280-ff45-11e9-9a9d-a332e2d40375.png)

**Comment by nabijaczleweli** [comment]
Released in [`v1.9.0`](https://github.com/thecoshman/http/releases/tag/v1.9.0)
